import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'
import LINKS from '../src/data/links'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MD-APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href={LINKS.NEXTJS_LINK}>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a
            href={LINKS.NEXTJS_DOCS_LINK}
            className={styles.card}
            target="_blank"
            rel="noreferrer noopener"
          >
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href={LINKS.NEXTJS_LEARN_LINK}
            className={styles.card}
            target="_blank"
            rel="noreferrer noopener"
          >
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href={LINKS.NEXTJS_EXAMPLES_LINK}
            className={styles.card}
            target="_blank"
            rel="noreferrer noopener"
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href={LINKS.NEXTJS_DEPLOY_LINK}
            className={styles.card}
            target="_blank"
            rel="noreferrer noopener"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

          <Link href="/test">
            <a className={styles.card}>
              <h2>Error Boundary &rarr;</h2>
              <p>Test React Error Boundary with a runtime error.</p>
            </a>
          </Link>

          <Link href="/counter">
            <a className={styles.card}>
              <h2>Counter App &rarr;</h2>
              <p>A simple counter app with Redux.</p>
            </a>
          </Link>

          <Link href="/todos">
            <a className={styles.card}>
              <h2>ToDo List App &rarr;</h2>
              <p>A simple todo list app with Redux.</p>
            </a>
          </Link>

          <Link href="/posts">
            <a className={styles.card}>
              <h2>Posts App &rarr;</h2>
              <p>A simple posts app with Redux.</p>
            </a>
          </Link>
        </div>

        <section className="max-w-screen-2xl p-4 mx-auto text-center">
          <a
            className="text-2xl"
            href={LINKS.TAILWINDCSS_DOCS_LINK}
            target="_blank"
            rel="noopener noreferrer"
          >
            TailwindCss is working! 🎉 🎉 🎉
          </a>
          <p className="my-4">
            <code>
              className=&quot;max-w-screen-2xl p-4 mx-auto text-center&quot;
            </code>
          </p>
        </section>
      </main>

      <footer className={styles.footer}>
        <a href={LINKS.VERCEL_LINK} target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
